### ISSUE TITLE
After registration, the user is able to login only once

### ISSUE THREAD

**Issue by ParagLawate** [jashwanth999/Authentication-using-blockchain#1]
While testing it, I found that after making a new user account and connecting it through metamask  the user is able to login only once. Entering the correct login credentials a second time , the web page gets refreshed.

**Comment by jashwanth999** [comment]
**you need to logout** , because i stored email in local storage .

```javascript
import "./App.css";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import SignIn from "./Screens/Signin";
import SignUp from "./Screens/Signup";
import Home from "./Screens/Home";

function App() {

  return (
    <div className="App">
      <BrowserRouter>
        <Routes>
          <Route exact path="/" element={<SignIn />} />
          <Route path="/Signup" element={<SignUp />} />
          <Route
            path="/Home"
            element={<Home />}
          />
        </Routes>
      </BrowserRouter>
    </div>
  );
}

export default App;
```

paste above code in **App.js** to solve your issue.

**Comment by ParagLawate** [comment]
Yes it works, but it gets stuck on this after log out
![image](https://user-images.githubusercontent.com/113654241/206240037-7ad3a00e-692d-4ce5-bb91-17de4176c28d.png)

**Comment by jashwanth999** [comment]
First , learn REACT.

nothing there , you need to navigate to home page once you click on logout

declare 

**const navigate = useNavigate()** in **Home.js**

once you click on LOGOUT , add **navigate(“/“)**
